### ISSUE TITLE
Stopped working recently, maybe Notion updated their API?

### ISSUE THREAD

**Issue by BoD** [notionsdk/notion-sdk-kotlin-old#1]
Hi!

I've noticed something that stopped working for a few days now. I make this call:
```kotlin
val page: NotionResponse = notion.loadPage(dashPageId)
```
and the resulting page has all its fields to `null` (see debugger screenshot):

<img width="526" alt="Screenshot 2020-06-09 11 47 23" src="https://user-images.githubusercontent.com/372852/84133183-24802800-aa47-11ea-9388-7e936bbcd4e9.png">

This used to work (for the same page id) a few days ago so I'm not sure what to conclude.

If there's anything I can do to help investigate this, don't hesitate to tell me!

**Comment by petersamokhin** [comment]
Hey!

There're a few potential reasons why that stopped working:
- this library was made as a small tool only for my needs. Anyone was able to improve or add something, but it's like a hardcoded workaround which can be broken at any time even by a small change in Notion API;
- it was made more than a year ago and it's based on a private API, so I think it should be broken a long time ago, but fortunately stopped working only now;
- Notion introduced public API which should be available soon, but only for paid plans, so maybe they added some additional security stuff to prevent people using their API for free.

For now, unfortunately, I don't think that it's a good idea to fix the library or make new.
So it's up to you :)

**Comment by BoD** [comment]
Thanks for replying!

While I generally agree to everything you said - would you accept to review/merge a PR if I find a fix?

**Comment by petersamokhin** [comment]
Yeah, of course. I would be grateful if you want to contribute 🙂

**Comment by BoD** [comment]
After several hours of fiddling ... actually my cookie was expired apparently 🤦‍♀️

When that happens instead of returning a `401` Notion's API returns empty objects . . . . . .

Using a recent cookie, everything works again.  

Thanks for your lib! :)
